config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :customers, controllers: { omniauth_callbacks: 'customers/omniauth_callbacks',
                                        registrations: 'customers/registrations',
                                        confirmations: 'customers/confirmations' }

  root to: 'pages#home'

  resources :addresses
  resources :customers, only: %i[edit]

  resources :categories, only: %i[index show] do
    resources :books, only: %i[index show]
  end

  get '/api/health', to: proc { [200, {}, ['Healthy']] }

  resources :checkouts, only: %i[show update]
  resources :coupons, only: %i[create destroy]
  resources :carts, only: %i[destroy show update] do
    resources :coupons
  end
  resources :books, only: [] do
    resources :reviews
  end

  resources :orders, only: %i[show]
  resources :carts, only: %i[index]
  resources :line_items, only: %i[create show destroy] do
    post 'add', to: 'line_items#add_quantity', as: 'add', on: :member
    post 'reduce', to: 'line_items#reduce_quantity', as: 'reduce', on: :member
  end

  match '*unmatched', to: 'application#not_found', constraints: lambda { |req|
    req.path.exclude? 'rails/active_storage'
  }, via: :all
end

app/models/book.rb
# frozen_string_literal: true

class Book < ApplicationRecord
  AVAILABLE_FILTERS = {
    I18n.t('book_sort.newest_first') => 'newest_first',
    I18n.t('book_sort.popular_first') => 'popular_first',
    I18n.t('book_sort.price_low_to_high') => 'price_low_to_high',
    I18n.t('book_sort.price_high_to_low') => 'price_high_to_low',
    I18n.t('book_sort.alphabetically') => 'alphabetically',
    I18n.t('book_sort.analphabetically') => 'analphabetically'
  }.freeze

  scope :newest_first, -> { order(created_at: :desc) }
  scope :popular_first, -> { order(created_at: :asc) }
  scope :price_low_to_high, -> { order(price: :asc) }
  scope :price_high_to_low, -> { order(price: :desc) }
  scope :alphabetically, -> { order(title: :asc) }
  scope :analphabetically, -> { order(title: :desc) }

  scope :latest, -> { order(:created_at).last(3) }

  has_many :book_authors, dependent: :destroy
  has_many :authors, through: :book_authors
  has_many :reviews, dependent: :destroy
  has_many_attached :images
  belongs_to :category
  belongs_to :material

  has_many :line_items, dependent: :destroy

  validates :title, presence: true
  validates :price, presence: true
  validates :quantity, presence: true

  def self.most_popular_books(quantity = 4)
    Book.find(LineItem.group(:book_id).sum(:quantity).first(quantity).to_h.keys)
  end
end

app/controllers/books_controller.rb
# frozen_string_literal: true

class BooksController < ApplicationController
  decorates_assigned :book

  def show
    @book = BookDecorator.find_by(id: params[:id], category_id: params[:category_id])
  end
end

app/views/books/show.html.haml
%main.container
  = link_to 'Back to results', category_path(@book.category_id)
  .row
    .col-sm-6
      .product-gallery
        .mb-20
          %img.img-responsive
            = image_tag url_for(book.images.first)
        .images.clearfix
        - book.images.limit(3).each do |image|
          %a.img-link
            = image_tag url_for(image)
    .col-sm-6
      %h1.mt-res-0
        = book.title
      %p.lead.small
        = book.authors_names
    .col-sm-6
      %h1.mt-res-0
        %p.lead.small
          = I18n.t('book.piece', count: book.quantity)
          %button.btn.btn-sm.btn-success#decrease-quantity -
          %button.btn.btn-sm.btn-success#increase-quantity +
      .row
        .col-xs-12.col-md-4
          %p.h1.in-gold-500.mt-10#book-cost
            = number_to_currency( @book.price, unit: '€')
        .col-xs-5.col-md-3
          .input-group.general-position
            %input.form-control#quantity-input{ value: 1 }
              %input.form-control.hidden#book-price{ value: "#{@book.price}" }
        .col-xs-7.col-md-5
          %button.btn.btn-default.pull-right.general-position
            = button_to "Add to Cart", line_items_path(book_id: book.id), class: 'btn-default'
      .general-info-wrap.divider-lg
        %p
          = t 'book.description'
        %p.lead.small.line-height-2
          = truncate(book.description, length: 25)
          %a.in-gold-500.ml-10
            = link_to 'Read more', '', class: "read-more-#{book.id}"
      .general-info-wrap.divider-lg
        .clearfix
          %p.pull-left
            = t 'book.year_of_publication'
          %p.lead.small.pull-right
            =  book.issue_date
      .general-info-wrap.divider-lg
        .clearfix
          %p.pull-left
            = t 'book.dimensions'
          %p.lead.small.pull-right
            = book.dimensions
      .general-info-wrap.divider-lg
        .clearfix
          %p.pull-left
            = t 'book.materials'
          %p.lead.small.pull-right
            = book.material.name
  .mb-80
  - if customer_signed_in?
    %h3
      = t 'review.write_a_review'
    %p.general-info-text
      = t 'review.score'
    .mb-15
      = render 'reviews/form'
    %h3.in-gold-500.mb-25 Reviews (#{@book.reviews.approved.count})
    = render 'reviews/reviews'