config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :customers, controllers: { omniauth_callbacks: 'customers/omniauth_callbacks',
                                        registrations: 'customers/registrations',
                                        confirmations: 'customers/confirmations' }

  root to: 'pages#home'

  resources :addresses
  resources :customers, only: %i[edit]

  resources :categories, only: %i[index show] do
    resources :books, only: %i[index show]
  end

  get '/api/health', to: proc { [200, {}, ['Healthy']] }

  resources :checkouts, only: %i[show update]
  resources :coupons, only: %i[create destroy]
  resources :carts, only: %i[destroy show update] do
    resources :coupons
  end
  resources :books, only: [] do
    resources :reviews
  end

  resources :orders, only: %i[show]
  resources :carts, only: %i[index]
  resources :line_items, only: %i[create show destroy] do
    post 'add', to: 'line_items#add_quantity', as: 'add', on: :member
    post 'reduce', to: 'line_items#reduce_quantity', as: 'reduce', on: :member
  end

  match '*unmatched', to: 'application#not_found', constraints: lambda { |req|
    req.path.exclude? 'rails/active_storage'
  }, via: :all
end

app/models/cart.rb
# frozen_string_literal: true

class Cart < ApplicationRecord
  AVAILABLE_FILTERS = {
    I18n.t('order_sort.waiting_for_processing') => 'waiting_for_processing',
    I18n.t('order_sort.in_delivery') => 'in_delivery',
    I18n.t('order_sort.delivered') => 'delivered',
    I18n.t('order_sort.canceled') => 'canceled'
  }.freeze

  has_many :line_items, dependent: :destroy
  has_many :books, through: :line_items
  has_many :addresses, as: :addressable, dependent: :destroy
  accepts_nested_attributes_for :addresses
  has_one :coupon, dependent: :destroy

  belongs_to :customer, optional: true
  belongs_to :delivery, optional: true
  belongs_to :credit_card, optional: true

  after_create :set_number_and_status

  enum status: { waiting_for_processing: 0, in_delivery: 1, delivered: 2, canceled: 3 }

  def sub_total
    line_items.sum(&:total_price)
  end

  def discount
    coupon ? sub_total * coupon.discount_percent / 100 : 0.00
  end

  def order_total
    price_with_coupon = coupon ? sub_total - discount : sub_total
    delivery ? price_with_coupon + delivery.price : sub_total
  end

  private

  def set_number_and_status
    update(number: "R#{id.to_s.rjust(8, '0')}")
  end
end

app/controllers/carts_controller.rb
# frozen_string_literal: true

class CartsController < ApplicationController
  before_action :show_filter, only: %i[index show]

  def index
    @orders = OrderSorter.call(params, current_customer.carts).reverse
  end

  def show; end

  def show_order; end

  private

  def show_filter
    @filter = params[:status] ? params[:status].to_s : OrderSorter::DEFAULT_FILTER
  end
end

app/views/carts/index.html.haml
%main.container.general-main-wrap
  %h1.mt-0.mb-25
    = I18n.t("order.my_orders")
  %p.lead.small.mb-10.visible-xs
    = I18n.t("order.sort_by")
  .dropdowns.dropdown.general-order-dropdown
    %a.dropdown-toggle.lead.small{href: "#", 'data-toggle': "dropdown", role: "button", 'aria-haspopup': "true", 'aria-expanded': "false"}
      = I18n.t("order_sort.#{@filter}")
      %i.fa.fa-angle-down.dropdown-icon.pull-right
    %ul.dropdown-menu
      - Cart::AVAILABLE_FILTERS.each_value do |filter|
        %li
          = link_to I18n.t("order_sort.#{filter.to_s}"), carts_path(status: filter)
  .visible-xs
    - @orders.each do |order|
      .general-cart-item.divider-lg-bottom.pt-0
        %table.table
          %tr
            %td.col-half
              %span.in-grey-600
                = I18n.t("order.number")
            %td.col-half
              %span.general-order-number
                = order.number
          %tr
            %td
              %span.in-grey-600
                = I18n.t("order.completed_at")
            %td
              %span.in-grey-900.font-16.fw-300
                = order.created_at.strftime('%Y-%m-%d')
          %tr
            %td
              %span.in-grey-600
                = I18n.t("order.status")
            %td
              %span.font-16.in-grey-900.fw-300
                = order.status.tr('_', ' ').capitalize
          %tr
            %td
              %span.in-grey-600
                = I18n.t("order.total")
            %td
              %strong.font-16
                = number_to_currency(order.order_total, unit: '€')
  .hidden-xs.mb-res-50
    %table.table.table-hover
      %thead
        %tr
          %th
            %span.in-grey-600
              = I18n.t("order.number")
          %th
            %span.in-grey-600
              = I18n.t("order.completed_at")
          %th
            %span.in-grey-600
              = I18n.t("order.status")
          %th
            %span.in-grey-600
              = I18n.t("order.total")
        %tbody
          - @orders.each do |order|
            %tr
              %td
                %span.general-order-number
                  = link_to order_path(order), class: "general-order-number" do
                    = order.number
              %td
                %span.in-grey-900.font-16.fw-300
                  = order.created_at.strftime('%Y-%m-%d')
              %td
                %span.font-16.in-grey-900.fw-300
                  = order.status.tr('_', ' ').capitalize
              %td
                %strong.font-16
                  = number_to_currency(order.order_total, unit: '€')

app/views/carts/show.html.haml
%main.container.general-main-wrap
  %h1.general-title-margin Cart
  - if current_cart.line_items.empty?
    .text-center
      %p.font-18 Cart is empty
      = link_to "Go to Store", categories_path, class: "btn btn-default mb-20"
  - else
    - current_cart.line_items.each do |line_item|
      .visible-xs
        .general-cart-item.divider-lg-bottom
          = link_to "Empty cart", cart_path(current_cart),method: :delete, data: {confirm: "Are you sure?"}
          %button.close.general-cart-close{type: "button", 'aria-label': "Close"}
            = link_to line_item_path(line_item), method: :delete, type: "button", 'aria-label': "Close" do
              %span{'aria-hidden': "true"} &times;
          %p.title
            = line_item.book.title
          %table.table
            %tr
              %td
                %span.in-grey-600 Price
              %td
                %span.font-16.in-gold-500= number_to_currency(line_item.book.price, unit: '€')
            %tr
              %td.vertical-middle
                %span.in-grey-600 Quantity
              %td
                .input-group
                  = link_to reduce_line_item_path(id: line_item), method: :post do
                    %i.fa.fa-minus.line-heaght-40
                  %input.quantity-input{ value: "#{line_item.quantity}", type: "text"}
                  = link_to add_line_item_path(id: line_item), method: :post do
                    %i.fa.fa-plus.line-heaght-40
            %tr
              %td
                %span.in-grey-600 SubTotal
              %td
                %span.font-16.in-gold-500
                  = number_to_currency(current_cart.sub_total, unit: '€')
      .hidden-xs
        %table.table.table-hover
          %tr.no-hover
            %th.col-pic.pl-0
              %span.in-grey-600 Product
            %th.col-title
            %th.col-price
              %span.in-grey-600 Price
            %th.col-quantity
              %span.in-grey-600 Quantity
            %th.col-total
              %span.in-grey-600 SubTotal
            %th.col-close
          %tr
            %td
              .general-img-wrap-table
                = link_to category_book_path(line_item.book.category_id, line_item.book.id) do
                  %img.cart-img-shadow.pull-left
                    = image_tag url_for(line_item.book.images.first)
            %td
              %p.title
                = link_to category_book_path(line_item.book.category_id, line_item.book.id) do
                  = line_item.book.title
            %td
              %span.font-16.in-gold-500= number_to_currency(line_item.book.price, unit: '€')
            %td
              .input-group
                = link_to reduce_line_item_path(id: line_item), method: :post do
                  %i.fa.fa-minus.line-heaght-40#reduce_qty
                %input.quantity-input{value: "#{line_item.quantity}", type: "text"}
                = link_to add_line_item_path(id: line_item), method: :post do
                  %i.fa.fa-plus.line-heaght-40#add_qty
            %td
              %span.font-16.in-gold-500= number_to_currency(line_item.total_price, unit: '€')
            %td
              %button.close.general-cart-close
                = link_to line_item_path(line_item), method: :delete, type: "button", 'aria-label': "Close" do
                  %span{'aria-hidden': "true"} &times;
    .general-order-wrap
      .row
        .col-sm-4
          = render 'coupons/coupon_form'
        .col-sm-8
          .res-mr-200.text-center.general-text-right
            %p.in-gold-500.font-18 Order Summary
            %table.general-summary-table.general-summary-table-right.general-text-right
              %tr
                %td
                  %p.font-16 Subtotal:
                %td
                  %p.font-16
                    = number_to_currency(current_cart.sub_total, unit: '€')
              %tr
                %td
                  %p.font-16 Coupon:
                %td
                  %p.font-16
                    = number_to_currency(current_cart.discount, unit: '€')
              %tr
                %td
                  %strong.font-18 Order Total:
                %td
                  %strong.font-18
                    = number_to_currency(current_cart.order_total, unit: '€')
          %button.btn.btn-default.mb-20.visible-xs-inline-block
            = link_to "Checkout", checkout_path(:login), class: 'btn-default'
        %button.btn.btn-default.mb-20.hidden-xs.center-block
          = link_to "Checkout", checkout_path(:login), class: 'btn-default'

app/views/carts/show_order.html.haml
%main.container.general-main-wrap
  %h1.general-title-margin
    = @order.number
  .row.mb-20
    - @order.addresses.each do |current_address|
      .col-sm-3
        %h3.general-subtitle= current_address.address_type.capitalize
        %p.general-address
          = current_address.first_name
          = current_address.last_name
          %br
          = current_address.address
          %br
          = current_address.zipcode
          %br
          = current_address.country
          %br
          = current_address.phone
    .col-sm-3
      %h3.general-subtitle
        = I18n.t("checkout.shipments")
      %p.general-address
        = @order.delivery.name
        %br
        = @order.delivery.time
        %br
        = number_to_currency(@order.delivery.price, unit: '€')
    .col-sm-3
      %h3.general-subtitle
        = I18n.t("checkout.payment_information")
      %p.general-address
        ** ** ** #{@order.credit_card.number.last(4)}
        %br
        = @order.credit_card.month_year
  .visible-xs
    - @order.line_items.each do |line_item|
      .general-cart-item.divider-lg
        .general-img-wrap-table
          %img.cart-img-shadow
            = image_tag url_for(line_item.book.images.first)
        %p.title
          = line_item.book.title
        %P.in-grey-600.fw-300
          = line_item.book.description.split('.').first
        %table.table
          %tr
            %td
              %span.in-grey-600
                = I18n.t("delivery.price")
            %td
              %span.font-16.in-gold-500
                = number_to_currency(line_item.book.price, unit: '€')
          %tr
            %td.vertical-middle
              %span.in-grey-600
                = I18n.t("checkout.quantity")
            %td
              %span
                = line_item.quantity
          %tr
            %td
              %span.in-grey-600
                = I18n.t("checkout.subtotal")
            %td
              %span.font-16.in-gold-500
                = number_to_currency(line_item.total_price, unit: '€')
  .hidden-xs.divider-lg.pt-20
    %table.table.table-hover
      %thead
        %tr
          %th
            %span.in-grey-600
              = I18n.t("checkout.book")
          %th.col-method
          %th
            %span.in-grey-600
              = I18n.t("checkout.delivery.price")
          %th
            %span.in-grey-600
              = I18n.t("checkout.quantity")
          %th
            %span.in-grey-600
              = I18n.t("checkout.total")
      %tbody
        - @order.line_items.each do |line_item|
          %tr
            %td
              .general-img-wrap-table
                %img.cart-img-shadow.pull-left
                  = image_tag url_for(line_item.book.images.first)
            %td
              %p.title
                = line_item.book.title
              %p.in-grey-600.fw-300
                = line_item.book.description.split('.').first
            %td
              %span.font-16.in-gold-500
                = number_to_currency(line_item.book.price, unit: '€')
            %td
              %span.ml-30
                = line_item.quantity
            %td
              %span.font-16.in-gold-500
                = number_to_currency(line_item.total_price, unit: '€')
  .text-center.general-text-right
    %p.in-gold-500.font-18
      = I18n.t("checkout.order_summary")
    %table.general-summary-table.general-summary-table-right.general-text-right
      %tr
        %td
          %p.font-16
            = I18n.t("checkout.subtotal")
        %td
          %p.font-16
            = number_to_currency(@order.sub_total, unit: '€')
      %tr
        %td
          %p.font-16
            = I18n.t("checkout.coupon")
        %td
          %p.font-16
            = number_to_currency(@order.discount, unit: '€')
      %tr
        %td
          %p.font-16
            = I18n.t("checkout.shipping")
        %td
          %p.font-16
            = number_to_currency(@order.delivery.price, unit: '€')
      %tr
        %td
          %strong.font-18
            = I18n.t("checkout.order_total")
        %td
          %strong.font-18
            = number_to_currency(@order.order_total, unit: '€')