config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :customers, controllers: { omniauth_callbacks: 'customers/omniauth_callbacks',
                                        registrations: 'customers/registrations',
                                        confirmations: 'customers/confirmations' }

  root to: 'pages#home'

  resources :addresses
  resources :customers, only: %i[edit]

  resources :categories, only: %i[index show] do
    resources :books, only: %i[index show]
  end

  get '/api/health', to: proc { [200, {}, ['Healthy']] }

  resources :checkouts, only: %i[show update]
  resources :coupons, only: %i[create destroy]
  resources :carts, only: %i[destroy show update] do
    resources :coupons
  end
  resources :books, only: [] do
    resources :reviews
  end

  resources :orders, only: %i[show]
  resources :carts, only: %i[index]
  resources :line_items, only: %i[create show destroy] do
    post 'add', to: 'line_items#add_quantity', as: 'add', on: :member
    post 'reduce', to: 'line_items#reduce_quantity', as: 'reduce', on: :member
  end

  match '*unmatched', to: 'application#not_found', constraints: lambda { |req|
    req.path.exclude? 'rails/active_storage'
  }, via: :all
end

app/controllers/checkouts_controller.rb
# frozen_string_literal: true

class CheckoutsController < ApplicationController
  include Wicked::Wizard

  before_action :login_step_authentication_check, :line_items_check, only: :show

  steps :login, :address, :delivery, :payment, :confirm, :complete

  def show
    @service = CheckoutService.new(current_cart, current_customer, step, cookies, params)
    @service.call
    move_to_right_step

    render_wizard
    empty_cart_if_order_done
  end

  def update
    @service = CheckoutService.new(current_cart, current_customer, step, cookies, params)
    render_wizard(@service, id: step)
  end

  private

  def login_step_authentication_check
    redirect_to wizard_path(next_step) if signed_at_login_step?
  end

  def signed_at_login_step?
    customer_signed_in? && step == :login
  end

  def line_items_check
    redirect_to root_path if current_cart.line_items.none?
  end

  def empty_cart_if_order_done
    session[:cart_id] = nil if cookies[:order_done] == true
  end

  def move_to_right_step
    jump_to(previous_step) if ConditionStepService.new(current_cart, step).call
  end
end

app/helpers/checkout_helper.rb
# frozen_string_literal: true

module CheckoutHelper
  def step_state(current_step)
    return 'active' if step_active?(current_step)

    'done' if step_done?(current_step)
  end

  def step_active?(current_step)
    current_step == step
  end

  def step_done?(current_step)
    past_step?(current_step)
  end
end

app/views/checkouts/_progress_bar.html.haml
%h1.general-title-margin
  = I18n.t('checkout.checkout')
%ul.steps.list-inline
  - wizard_steps[1,5].each_with_index do |step, index|
    %li.step{ class: step_state(step)}
      = link_to wizard_path(step), class: 'step-link' do
        %span.step-number
          = index + 1 unless step_done?(step)
          - if step_done?(step)
            %i.fa.fa-check.step-icon
        %span.step-text.hidden-xs= step.capitalize
    - unless step == :complete
      %li.step-divider

app/views/checkouts/address.html.haml
%main.container
  = render 'progress_bar'
  = simple_form_for @current_cart, url: wizard_path, method: :put, class: 'res-mb-100', defaults: { input_html: { class: 'form-control' }, required: false } do |f|
    .hidden-xs.hidden-sm
      .row
        .col-md-5
          %h3.general-subtitle
            = I18n.t('checkout.address.billing_address')
          %p.general-info-text
            = I18n.t('checkout.address.fields_required')
        .col-md-5.col-md-offset-1
          %h3.general-subtitle
            = I18n.t('checkout.address.shipping_address')
      .row
        .col-md-5.mb-40
          .visible-xs.visible-sm
            %h3.general-subtitle
              = I18n.t('checkout.address.billing_address')
            %p.general-info-text
              = I18n.t('checkout.address.fields_required')
          = f.simple_fields_for :billing, @service.billing do |ff|
            .form-group
              = ff.input :first_name, autocomplete: "off", placeholder: "First name"
            .form-group
              = ff.input :last_name, autocomplete: "off", placeholder: "Last name"
            .form-group
              = ff.input :address, autocomplete: "off", placeholder: "Address"
            .form-group
              = ff.input :city, autocomplete: "off", placeholder: "City"
            .form-group
              = ff.input :zipcode, autocomplete: "off", placeholder: "Zipcode"
            .form-group
              = ff.label :country, required: false
              %br/
              = ff.country_select(:country, { priority_countries: ["UA", "US"], priority_countries_divider: "~~~~~~"}, {autocomplete: "off", id: 'сountry', class: 'form-control' })
            .form-group
              = ff.input :phone, placeholder: "Example +355 66 123 4567"
        .col-md-5.col-md-offset-1#hidden_fields
          = f.simple_fields_for :shipping, @service.shipping do |ff|
            .form-group
              = ff.input :first_name, autocomplete: "off", placeholder: "First name"
            .form-group
              = ff.input :last_name, autocomplete: "off", placeholder: "Last name"
            .form-group
              = ff.input :address, autocomplete: "off", placeholder: "Address"
            .form-group
              = ff.input :city, autocomplete: "off", placeholder: "City"
            .form-group
              = ff.input :zipcode, autocomplete: "off", placeholder: "Zipcode"
            .form-group
              = ff.label :country, required: false
              %br/
              = ff.country_select(:country, { priority_countries: ["UA", "US"], priority_countries_divider: "~~~~~~"}, {autocomplete: "off", id: 'сountry', class: 'form-control' })
            .form-group
              = ff.input :phone, placeholder: "Example +355 66 123 4567"
    .row
      .col-md-5.mb-40
        .form-group.checkbox
          = f.input :use_billing, as: :boolean, type: "checkbox", label: I18n.t('checkout.address.use_billing_address'), checked_value: true, unchecked_value: nil, input_html: {class: 'checkbox-input', id: 'hide_address'}
    .general-text-align.mb-60
      %p.in-gold-500.font-18
        = I18n.t('checkout.payment_information')
      %table.general-summary-table
        %tr
          %td
            %p.font-16
              = I18n.t('checkout.item_total')
          %td
            %p.font-16
              = number_to_currency(current_cart.sub_total, unit: '€')
        %tr
          %td
            %p.font-16
              = I18n.t('checkout.coupon')
          %td
            %p.font-16
              = number_to_currency(current_cart.discount, unit: '€')
        %tr
          %td
            %p.font-16
              = I18n.t('checkout.shipping')
          %td
            %p.font-16
              = number_to_currency(current_cart.delivery ? current_cart.delivery.price : 0.00, unit: '€')
        %tr
          %td
            %p.font-16
              = I18n.t('checkout.order_total')
          %td
            %p.font-16
              = number_to_currency(current_cart.order_total, unit: '€')
      %button.btn.center-block.mb-20
        = f.submit "Save and Continue", class: 'btn btn-default.mb-10'

app/views/checkouts/complete.html.haml
%main.container.general-main-wrap
  = render 'progress_bar'
  .text-center.mb-40
    %h3.general-subtitle
      = I18n.t('checkout.complete.thank_you')
    %p.fw-300
      = I18n.t('checkout.complete.order_confirmation', email: current_customer.email)
  .row.mb-20
    .col-sm-6
      .visible-xs
        %p.general-order-number.mb-0 Order ##{current_cart.number}
        %p.general-address.mb-30
          = current_cart.created_at.strftime("%B %d, %Y")
      %p.general-address
        = current_cart.addresses.shipping.first.first_name
        = current_cart.addresses.shipping.first.last_name
        %span.general-edit edit
        %br
        = current_cart.addresses.shipping.first.address
        %br
        = current_cart.addresses.shipping.first.city
        %br
        = current_cart.addresses.shipping.first.country
        %br
        = current_cart.addresses.shipping.first.phone
    .col-sm-6.hidden-xs.text-right
      %p.general-order-number.mb-0 Order ##{current_cart.number}
      %p.general-address.mb-30
        = current_cart.created_at.strftime("%B %d, %Y")
  .visible-xs
    - current_cart.line_items.each do |line_item|
      .general-cart-item.divider-lg
        .general-img-wrap-table
          %img.cart-img-shadow
            = image_tag url_for(line_item.book.images.first)
        %p.title
          = line_item.book.title
        %P.in-grey-600.fw-300
          = line_item.book.description.split('.').first
        %table.table
          %tr
            %td
              %span.in-grey-600
                = I18n.t('checkout.delivery.price')
            %td
              %span.font-16.in-gold-500
                = number_to_currency(line_item.book.price, unit: '€')
          %tr
            %td.vertical-middle
              %span.in-grey-600
                = I18n.t('checkout.quantity')
            %td
              %span
                = line_item.quantity
          %tr
            %td
              %span.in-grey-600
                = I18n.t('checkout.subtotal')
            %td
              %span.font-16.in-gold-500
                = number_to_currency(line_item.total_price, unit: '€')
      .general-cart-item.divider-lg.mb-55
        .general-img-wrap-table
          %img.cart-img-shadow
            = image_tag url_for(line_item.book.images.first)
        %p.title
          = line_item.book.title
        %table.table
          %tr
            %td
              %span.in-grey-600
                = I18n.t('checkout.delivery.price')
            %td
              %span.font-16.in-gold-500
                = number_to_currency(line_item.book.price, unit: '€')
          %tr
            %td.vertical-middle
              %span.in-grey-600
                = I18n.t('checkout.quantity')
            %td
              %span
                = line_item.quantity
          %tr
            %td
              %span.in-grey-600
                = I18n.t('checkout.subtotal')
            %td
              %span.font-16.in-gold-500
                = number_to_currency(line_item.total_price, unit: '€')
  .hidden-xs.divider-lg.pt-20
    - current_cart.line_items.each do |line_item|
      %table.table.table-hover
        %thead
          %tr
            %th
              %span.in-grey-600
                = I18n.t('checkout.book')
            %th.col-method
            %th
              %span.in-grey-600
                = I18n.t('checkout.delivery.price')
            %th
              %span.in-grey-600
                = I18n.t('checkout.quantity')
            %th
              %span.in-grey-600
                = I18n.t('checkout.total')
        %tbody
          %tr
            %td
              .general-img-wrap-table
                %img.cart-img-shadow.pull-left
                  = image_tag url_for(line_item.book.images.first)
            %td
              %p.title Android Programming for Beginners
              %p.in-grey-600.fw-300
                = line_item.book.description.split('.').first
            %td
              %span.font-16.in-gold-500
                = number_to_currency(line_item.book.price, unit: '€')
            %td
              %span.ml-30
                = line_item.quantity
            %td
              %span.font-16.in-gold-500
                = number_to_currency(line_item.total_price, unit: '€')
  .text-center.general-text-right
    %p.in-gold-500.font-18
      = I18n.t('checkout.order_summary')
    %table.general-summary-table.general-summary-table-right.general-text-right
      %tr
        %td
          %p.font-16
            = I18n.t('checkout.order_summary')
        %td
          %p.font-16
            = number_to_currency(current_cart.sub_total, unit: '€')
      %tr
        %td
          %p.font-16
            = I18n.t('checkout.coupon')
        %td
          %p.font-16
            = number_to_currency(current_cart.discount, unit: '€')
      %tr
        %td
          %p.font-16
            = I18n.t('checkout.shipping')
        %td
          %p.font-16
            = number_to_currency(current_cart.delivery.price, unit: '€')
      %tr
        %td
          %strong.font-18
            = I18n.t('checkout.order_total')
        %td
          %strong.font-18
            = number_to_currency(current_cart.order_total, unit: '€')
  .text-center
    %button.btn.btn-default.mb-20
      = link_to "Back to Store", categories_path, class: "btn btn-default"

app/views/checkouts/confirm.html.haml
%main.container.general-main-wrap
  = render 'progress_bar'
  .row.mb-20
    - current_cart.addresses.each do |current_address|
      .col-sm-3
        %h3.general-subtitle= current_address.address_type.capitalize
        %p.general-address
          = current_address.first_name
          = current_address.last_name
          = link_to "edit", checkout_path(:address), class: "general-edit"
          %br
          = current_address.address
          %br
          = current_address.zipcode
          %br
          = current_address.country
          %br
          = current_address.phone
    .col-sm-3
      %h3.general-subtitle
        = I18n.t('checkout.shipments')
      %p.general-address
        = current_cart.delivery.name
        = link_to "edit", checkout_path(:delivery), class: "general-edit"
        %br
        = current_cart.delivery.time
        %br
        = number_to_currency(current_cart.delivery.price, unit: '€')
    .col-sm-3
      %h3.general-subtitle
        = I18n.t('checkout.payment_information')
      %p.general-address
        ** ** ** #{current_cart.credit_card.number.last(4)}
        = link_to "edit", checkout_path(:payment), class: "general-edit"
        %br
        = current_cart.credit_card.month_year
  .visible-xs
    - current_cart.line_items.each do |line_item|
      .general-cart-item.divider-lg
        .general-img-wrap-table
          %img.cart-img-shadow
            = image_tag url_for(line_item.book.images.first)
        %p.title
          = line_item.book.title
        %P.in-grey-600.fw-300
          = line_item.book.description.split('.').first
        %table.table
          %tr
            %td
              %span.in-grey-600
                = I18n.t('delivery.price')
            %td
              %span.font-16.in-gold-500
                = number_to_currency(line_item.book.price, unit: '€')
          %tr
            %td.vertical-middle
              %span.in-grey-600
                = I18n.t('checkout.quantity')
            %td
              %span
                = line_item.quantity
          %tr
            %td
              %span.in-grey-600
                = I18n.t('checkout.subtotal')
            %td
              %span.font-16.in-gold-500
                = number_to_currency(line_item.total_price, unit: '€')
  .hidden-xs.divider-lg.pt-20
    %table.table.table-hover
      %thead
        %tr
          %th
            %span.in-grey-600
              = I18n.t('checkout.book')
          %th.col-method
          %th
            %span.in-grey-600
              = I18n.t('checkout.delivery.price')
          %th
            %span.in-grey-600
              = I18n.t('checkout.quantity')
          %th
            %span.in-grey-600
              = I18n.t('checkout.total')
      %tbody
        - current_cart.line_items.each do |line_item|
          %tr
            %td
              .general-img-wrap-table
                %img.cart-img-shadow.pull-left
                  = image_tag url_for(line_item.book.images.first)
            %td
              %p.title
                = line_item.book.title
              %p.in-grey-600.fw-300
                = line_item.book.description.split('.').first
            %td
              %span.font-16.in-gold-500
                = number_to_currency(line_item.book.price, unit: '€')
            %td
              %span.ml-30= line_item.quantity
            %td
              %span.font-16.in-gold-500
                = number_to_currency(line_item.total_price, unit: '€')
  .text-center.general-text-right
    %p.in-gold-500.font-18
      = I18n.t('checkout.order_summary')
    %table.general-summary-table.general-summary-table-right.general-text-right
      %tr
        %td
          %p.font-16
            = I18n.t('checkout.order_summary')
        %td
          %p.font-16
            = number_to_currency(current_cart.sub_total, unit: '€')
      %tr
        %td
          %p.font-16
            = I18n.t('checkout.coupon')
        %td
          %p.font-16
            = number_to_currency(current_cart.discount, unit: '€')
      %tr
        %td
          %p.font-16
            = I18n.t('checkout.shipping')
        %td
          %p.font-16
            = number_to_currency(current_cart.delivery.price, unit: '€')
      %tr
        %td
          %strong.font-18
            = I18n.t('checkout.order_total')
        %td
          %strong.font-18
            = number_to_currency(current_cart.order_total, unit: '€')
  .text-center
    %button.btn.btn-default.mb-20
      = button_to 'Place Order', wizard_path, method: :put, class: 'btn btn-default'

app/views/checkouts/delivery.html.haml
%main.container.general-main-wrap
  = render 'progress_bar'
  %h3.general-subtitle
    = I18n.t('checkout.delivery.shipping_method')
  = simple_form_for @current_cart, url: wizard_path, method: :put, class: 'res-mb-100', defaults: { input_html: { class: 'form-control' }, required: false } do |f|
    .visible-xs
      .general-cart-item.divider-lg-bottom
        %table.table
          %tr
            %td.col-half
              %span.in-grey-600
                = I18n.t('checkout.delivery.method')
            %td.col-half
              = f.collection_radio_buttons :delivery_id, @service.delivery, :id, :name, {}, { checked: true } do |option|
                .form-group.radio.mt-0.mb-0
                  %label.radio-label
                    = option.label(class: 'radio-label') do
                      = option.radio_button(class: 'radio-input')
                      %span.radio-icon
                      %span.radio-text= option.object.name
    .hidden-xs.mb-res-50
      %table.table.table-hover
        %thead
          %tr
            %th.col-method
              %span.in-grey-600.ml-40
                = I18n.t('checkout.delivery.method')
            %th
              %span.in-grey-600
                = I18n.t('checkout.delivery.days')
            %th
              %span.in-grey-600
                = I18n.t('checkout.delivery.price')
        %tbody
          = f.collection_radio_buttons :delivery_id, @service.delivery, :id, :name, {}, { checked: true } do |option|
            %tr
              %td
                .form-group.radio.mt-0.mb-0
                = option.radio_button(class: 'radio-icon')
                %span.radio-text
                  = option.object.name
              %td
                %span= option.object.time
              %td
                %span.font-16.in-gold-500= number_to_currency(option.object.price, unit: '€')
    .general-text-align
      %p.in-gold-500.font-18
        = I18n.t('checkout.order_summary')
      %table.general-summary-table
        %tr
          %td
            %p.font-16
              = I18n.t('checkout.order_summary')
          %td
            %p.font-16
              = number_to_currency(current_cart.sub_total, unit: '€')
        %tr
          %td
            %p.font-16
              = I18n.t('checkout.coupon')
          %td
            %p.font-16
              = number_to_currency(current_cart.discount, unit: '€')
        %tr
          %td
            %p.font-16
              = I18n.t('checkout.shipping')
          %td
            %p.font-16
              = number_to_currency(current_cart.delivery ? current_cart.delivery.price : 0.00, unit: '€')
        %tr
          %td
            %strong.font-18
              = I18n.t('checkout.order_total')
          %td
            %strong.font-18
              = number_to_currency(current_cart.order_total, unit: '€')
    .actions.text-center
      = f.submit 'Save and Continue', class: 'btn btn-default mb-20'

app/views/checkouts/login.html.haml
%main.container
  .row
    .col-md-5.mb-40
      .text-center
        %h3.general-subtitle Returning Customer
        = link_to customer_facebook_omniauth_authorize_path, method: :post, class: 'general-login-icon' do
          %i.fab.fa-facebook.fa-3x.mx-2
        %p.general-login-text or
      %form.general-form
        .mb-40
          %p.mb-15 Log In with Password
      = form_for(resource, as: resource_name, url: session_path(resource_name), html: {class: 'general-form'}) do |f|
        .form-group.mb-30
          = f.label :email, class: 'control-label input-label', html: {  'data-bar' => 'Enter Email' }
          = f.email_field :email, autofocus: true, autocomplete: "email", id: 'email', class: 'form-control', placeholder: "Enter Email"
        .form-group.mb-30
          = f.label :password, class: 'control-label input-label', html: { 'data-bar' => 'Password' }
          = f.password_field :password, autocomplete: "off", id: 'password', class: 'form-control', placeholder: "Password"
          - if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations'
            = link_to "Forgot password?", new_password_path(resource_name), class: 'help-block in-gold-500'
            = f.submit "Log In with Password", class: 'btn btn-default mb-20'
    .col-md-5.col-md-offset-1.mb-60
      .text-center
        %h3.general-subtitle New Customer
        %a.general-login-icon
        = link_to customer_facebook_omniauth_authorize_path, method: :post, class: 'general-login-icon' do
          %i.fab.fa-facebook.fa-3x.mx-2
        %p.general-login-text or
      %form.general-form
      = form_for(resource, as: resource_name, url: registration_path(resource_name), html: {class: 'general-form'}) do |f|
        = render partial: 'devise/shared/error_messages'
        .mb-40
          %p.mb-5 Quik Register
          %p.general-info-text.font-12.mb-20 You’ll be able to create password later
        .form-group.mb-30
          = f.label :email, class: 'control-label input-label', html: {  'data-bar' => 'Enter Email' }
          = f.email_field :email, autofocus: true, autocomplete: "email", id: 'email', class: 'form-control', placeholder: "Enter Email"
        .form-group.mb-30
          = f.password_field :password, autocomplete: "off", id: 'password', type: 'hidden', class: 'form-control', value: "Password123"
          = f.password_field :password_confirmation, autocomplete: "off", type: 'hidden', id: 'password_confirmation', class: 'form-control', placeholder: "Confirm Password", value: "Password123"
        .text-center
          = f.submit "Continue to Checkout", class: 'btn btn-default mb-20'

app/views/checkouts/payment.html.haml
%main.container.mb-res-50
  = render 'progress_bar'
  %h3.general-subtitle
    = I18n.t('checkout.credit_card')
  = simple_form_for @current_cart, url: wizard_path, method: :put, class: 'res-mb-100', defaults: { input_html: { class: 'form-control' }, required: false } do |f|
    = f.simple_fields_for :credit_card, @current_cart.credit_card do |ff|
      .row
        .col-sm-6
          = ff.input :number, placeholder: "Card Number", input_html: {'data-mask': '1234-1234-1234-1234'}
          .col-sm-6
            = ff.input :name_on_card, placeholder: "Name on Card"
          .col-sm-3
            = ff.input :month_year, placeholder: "MM / YY", input_html: { 'data-mask': '1111' }
          .col-sm-3
            = ff.input :cvv, placeholder: "CVV", input_html: { "data-tooltip" => true, :class => "has-tip", :title => "3-digit security code, usually found on the back of your card. American Express cards has 4-digit code, located on the front" }
      .general-text-align
        %p.in-gold-500.font-18
          = I18n.t('checkout.order_summary')
        %table.general-summary-table
          %tr
            %td
              %p.font-16
                = I18n.t('checkout.subtotal')
            %td
              %p.font-16
                = number_to_currency(current_cart.sub_total, unit: '€')
          %tr
            %td
              %p.font-16
                = I18n.t('checkout.coupon')
            %td
              %p.font-16
                = number_to_currency(current_cart.discount, unit: '€')
          %tr
            %td
              %p.font-16
                = I18n.t('checkout.shipping')
            %td
              %p.font-16
                = number_to_currency(current_cart.delivery ? current_cart.delivery.price : 0.00, unit: '€')
          %tr
            %td
              %strong.font-18
                = I18n.t('checkout.order_total')
            %td
              %strong.font-18
                = number_to_currency(current_cart.order_total, unit: '€')
    .actions.text-center
      = f.submit 'Save and Continue', class: 'btn btn-default mb-20'