config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :customers, controllers: { omniauth_callbacks: 'customers/omniauth_callbacks',
                                        registrations: 'customers/registrations',
                                        confirmations: 'customers/confirmations' }

  root to: 'pages#home'

  resources :addresses
  resources :customers, only: %i[edit]

  resources :categories, only: %i[index show] do
    resources :books, only: %i[index show]
  end

  get '/api/health', to: proc { [200, {}, ['Healthy']] }

  resources :checkouts, only: %i[show update]
  resources :coupons, only: %i[create destroy]
  resources :carts, only: %i[destroy show update] do
    resources :coupons
  end
  resources :books, only: [] do
    resources :reviews
  end

  resources :orders, only: %i[show]
  resources :carts, only: %i[index]
  resources :line_items, only: %i[create show destroy] do
    post 'add', to: 'line_items#add_quantity', as: 'add', on: :member
    post 'reduce', to: 'line_items#reduce_quantity', as: 'reduce', on: :member
  end

  match '*unmatched', to: 'application#not_found', constraints: lambda { |req|
    req.path.exclude? 'rails/active_storage'
  }, via: :all
end

app/views/layouts/_footer.html.haml
%footer.navbar-inverse
  .container
    .row
      .col-sm-9
        %ul.list-inline.general-align.mb-25
          %li
            = link_to t(:home), root_path, class: 'nav-link'
          %li
            = link_to t(:shop), categories_path, class: 'nav-link'
          %li
            %a.nav-link{href: "#"}
              = t :orders
          %li
            %a.nav-link{href: "#"}
              = t :settings
      .col-sm-3
        %p.general-nav-mail
          = t :nav_mail
        %p.general-nav-number
          = t :nav_number

app/views/layouts/_header.html.haml
%header.navbar.navbar-default
  .container
    .navbar-header
      %button.navbar-toggle.pull-left{type: "button", 'data-toggle': "collapse", 'data-target': "#navbar"}
        %span.sr-only
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to t(:title), root_path, class: 'navbar-brand'
      %a.shop-link.pull-right.visible-xs{href: cart_path(@current_cart)}
        %span.shop-icon
          %span.shop-quantity
            = @current_cart.line_items.count
    %a.shop-link.pull-right.hidden-xs{href: cart_path(@current_cart)}
      %span.shop-icon
        %span.shop-quantity
          = @current_cart.line_items.count
    #navbar.navbar-collapse.collapse.pl-30{'aria-expanded': "false"}
      .hidden-xs
        %ul.nav.navbar-nav
          %li
            = link_to t(:home), root_path
          %li.dropdown
            %a.dropdown-toggle#navigation{href: categories_path, 'data-toggle': "dropdown", role: "button", 'aria-haspopup': "true", 'aria-expanded': "true"}
              = t :shop
            %ul.dropdown-menu{"aria-labelledby" => "navigation"}
              - categories.each do |category|
                %li
                  = link_to category.title, category_path(category, status: BookSorter::DEFAULT_FILTER)
              - if customer_signed_in?
                %li.divider{role: "separator"}
                  %li
                    = link_to I18n.t(:log_out), destroy_customer_session_path, method: :delete
          %li.dropdown
            %a.dropdown-toggle#account{href: new_customer_session_path, 'data-toggle': "dropdown", role: "button", 'aria-haspopup': "true", 'aria-expanded': "false"}
              = t :my_account
            %ul.dropdown-menu{"aria-labelledby" => "account"}
              - if customer_signed_in?
                Hello, #{current_customer.email}
                %li
                  = link_to 'Settings', edit_customer_registration_path
                  = link_to 'My Orders', carts_path
                  = link_to 'Sign Out', destroy_customer_session_path, method: :delete
              - else
                %li
                  = link_to 'Sign In', new_customer_session_path
                  = link_to 'Sign up', new_customer_registration_path
      .visible-xs
        %button.close{type: "button", 'aria-label': "Close"}
          %span{'aria-hidden': "true"} &times;
        %ul.nav.navbar-nav
          %li
            = link_to t(:home), root_path
          %li
            %a{type: "button", 'data-toggle': "collapse", href: "#menu", 'aria-expanded': "false", 'aria-controls': "menu"}
              = t :shop
            %ul#menu.collapse.list-unstyled.pl-30.mb-10{'aria-expanded': "false"}
              - categories.each do |category|
                %li
                  = link_to category.title, category_path(category, status: BookSorter::DEFAULT_FILTER)
          %li
            = link_to 'My account', new_customer_session_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{charset: "UTF-8"}
    %meta{name: "viewport", content: "width=device-width"}
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title
      = t :title
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/header'
    - if notice
      .alert.alert-success.text-center= notice
    - if alert
      .alert.alert-danger.text-center= alert
    = yield
    = render 'layouts/footer'